services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VITE_API_URL=https://localhost:3001/api/parse-monobank
        - VITE_USE_HTTPS=true
        - VITE_DOMAIN=localhost
        - VITE_MONOBANK_JAR_URL=https://send.monobank.ua/jar/7dAsGZXPRB
        - VITE_UPDATE_INTERVAL=15000
        - VITE_NOTIFICATION_THRESHOLD_TARGET_PERCENT=1
        - VITE_NOTIFICATION_THRESHOLD_CURRENT_PERCENT=1
        - VITE_NOTIFICATION_THRESHOLD_ABSOLUTE=1
        - VITE_NOTIFICATION_PERMISSION_CHECK_INTERVAL=2000
    container_name: monobank-donate-frontend
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
    networks:
      - monobank-network
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_MONOBANK_JAR_URL=https://send.monobank.ua/jar/7dAsGZXPRB
      - VITE_UPDATE_INTERVAL=15000
      - VITE_NOTIFICATION_THRESHOLD_TARGET_PERCENT=1
      - VITE_NOTIFICATION_THRESHOLD_CURRENT_PERCENT=1
      - VITE_NOTIFICATION_THRESHOLD_ABSOLUTE=1
      - VITE_NOTIFICATION_PERMISSION_CHECK_INTERVAL=2000

    volumes:
      - C:\GIT\monobank-donate\ssl\server.crt:/etc/nginx/ssl/server.crt:ro
      - C:\GIT\monobank-donate\ssl\server.key:/etc/nginx/ssl/server.key:ro

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: monobank-donate-backend
    environment:
      - NODE_ENV=production
      - USE_HTTPS=true
      - SSL_KEY_PATH=/app/ssl/server.key
      - SSL_CERT_PATH=/app/ssl/server.crt
      - ALLOWED_ORIGINS=https://localhost,https://localhost:443
      - DEFAULT_JAR_URL=https://send.monobank.ua/jar/7dAsGZXPRB
      - CACHE_TTL=15
      - DOMAIN=localhost
      - RATE_LIMIT_GLOBAL_MAX=1000
      - RATE_LIMIT_PARSE_MAX=100
      - RATE_LIMIT_BRUTEFORCE_MAX=50
      - REQUEST_SIZE_LIMIT=10kb
      - PUPPETEER_NAVIGATION_TIMEOUT=30000
      - PUPPETEER_WAIT_TIMEOUT=15000
      - PUPPETEER_STATS_TIMEOUT=10000
      - MAX_RETRIES=3
      - RETRY_INITIAL_DELAY=1000
      - SCREENSHOTS_ENABLED=true
      - SCREENSHOTS_PATH=monobank-error.png
      - PORT=3001

    ports:
      - "3001:3001"
    networks:
      - monobank-network
    restart: unless-stopped
    volumes:
      - C:\GIT\monobank-donate\ssl\server.crt:/app/ssl/server.crt:ro
      - C:\GIT\monobank-donate\ssl\server.key:/app/ssl/server.key:ro

networks:
  monobank-network:
    driver: bridge